GET http://www.omdbapi.com/?apikey=4b925bd5&s=god-of-war&type=game HTTP/1.1
// chiamata con parametro s--> "terminator" prima pagina
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=nightmare HTTP/1.1
// chiamata con parametro s--> "nightmare" prima pagina
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=terminator&page=2 HTTP/1.1
// chiamata con parametro s--> "terminator" seconda pagina
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=nightmare&page=2 HTTP/1.1
// chiamata con parametro s--> "nightmare" seconda pagina
###

GET http://www.omdbapi.com/?apikey=4b925bd5&t=nightmare&page=2&y=2000 HTTP/1.1
// chiamata con parametro s--> "nightmare" + seconda pagina + usciti nel 2000
###

GET http://www.omdbapi.com/?apikey=4b925bd5&t=sun HTTP/1.1
// chiamata con parametro t--> "sun"
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=titans&type=game HTTP/1.1
//chiamata con parametro di ricerca s--> "titans" e parametro type--> "game"
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=game-of-thrones&type=series HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=X-men&type=movie HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=Lord%20of%20the%20rings&type=movie HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=Fantastic%20four&type=game HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=Justice%20League&type=movie HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=Rocky&type=movie HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=creed&type=movie HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=transformers&type=movie HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=The%20Lord%20of%20the%20Rings&type=movie HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=The%20Lord%20of%20the%20Rings&type=game HTTP/1.1
###

GET http://www.omdbapi.com/?apikey=4b925bd5&s=The%20Hobbit&type=movie HTTP/1.1
###





